using System;
using System.Numerics;
using System.Runtime.CompilerServices;
using Dalamud.Bindings.ImGui;
using Dalamud.Interface.Windowing;
using DynamicTextureManager.Interop;
using DynamicTextureManager.ModGeneration;
using OtterGui.Extensions;
using OtterGui.Services;
using OtterGui.Text;

namespace DynamicTextureManager.UI;

public class ConfigWindowPosition : IService
{
    public bool IsOpen { get; set; }
    public Vector2 Position { get; set; }
    public Vector2 Size { get; set; }
}

public class ConfigWindow : Window, IDisposable
{
    private readonly Configuration _configuration;
    private readonly ConfigWindowPosition _position;
    private readonly PenumbraService _penumbra;
    private readonly OverlayModManager _overlayMods;

    public ConfigWindow(Configuration configuration, ConfigWindowPosition position, PenumbraService penumbra, OverlayModManager overlayMods)
        : base("Dynamic Texture Manager: Configuration")
    {
        SizeConstraints = new WindowSizeConstraints
        {
            MinimumSize = new Vector2(600, 400),
            MaximumSize = new Vector2(600, 400)
        };

        _configuration = configuration;
        _position = position;
        _penumbra = penumbra;
        _overlayMods = overlayMods;
    }

    public void Dispose() { }

    public override void Draw()
    {
        _position.Size = ImGui.GetWindowSize();
        _position.Position = ImGui.GetWindowPos();
        
        Checkbox("Auto Rebuild"u8, "Automatically rebuild the generated mod shortly after edits, once it has been built with the hammer button."u8,
            _configuration.AutoReload, v => _configuration.AutoReload = v);

        Checkbox("Delete Mod With dTexture"u8, "When a dTexture is deleted, also delete its generated mod from Penumbra."u8,
            _configuration.DeleteModWithDTexture, v => _configuration.DeleteModWithDTexture = v);

        var maxColors = _configuration.DefaultDecalMaxColors;
        ImGui.SetNextItemWidth(150 * ImUtf8.GlobalScale);
        if (ImUtf8.Slider("##defaultMaxColors"u8, ref maxColors, "%d"u8, 2, 12))
        {
            _configuration.DefaultDecalMaxColors = maxColors;
            _configuration.Save();
        }

        ImGui.SameLine();
        ImUtf8.LabeledHelpMarker("Default Decal Colors"u8,
            "How many colors newly added colorset decals extract from their image at most.\nEach color claims one free colorset row; the cap can be changed per decal afterwards."u8);

        ImGui.Spacing();
        DrawPenumbraStatus();
        ImGui.Spacing();
        DrawOrphanedMods();
    }

    private void DrawOrphanedMods()
    {
        if (!_penumbra.Available)
            return;

        var orphans = _overlayMods.GetOrphanedMods();
        if (orphans.Count == 0)
            return;

        ImGui.Separator();
        ImUtf8.Text("Orphaned Generated Mods"u8);
        ImUtf8.HoverTooltip("Mods generated by this plugin that no dTexture references anymore.\nThey keep working in Penumbra, but the plugin can no longer rebuild them."u8);

        foreach (var ((directory, name), idx) in orphans.WithIndex())
        {
            using var id = ImUtf8.PushId(idx);
            ImUtf8.Text($"{name} ({directory})");
            ImGui.SameLine();
            if (ImUtf8.SmallButton("Open"u8))
                _penumbra.OpenModInPenumbra(directory);
            ImGui.SameLine();
            if (ImUtf8.SmallButton("Delete"u8) && ImGui.GetIO().KeyCtrl)
                _overlayMods.DeleteOrphan(directory);
            if (ImGui.IsItemHovered())
                ImUtf8.HoverTooltip("Hold Control and click to delete this mod from Penumbra permanently."u8);
        }
    }

    private void DrawPenumbraStatus()
    {
        ImGui.Separator();
        ImUtf8.Text("Penumbra"u8);
        if (!_penumbra.Available)
        {
            ImUtf8.Text("Not connected — is Penumbra installed and enabled?"u8);
            return;
        }

        ImUtf8.Text($"API Version: {_penumbra.Version.Breaking}.{_penumbra.Version.Features}");
        try
        {
            ImUtf8.Text($"Mod Directory: {_penumbra.GetModDirectory()}");
        }
        catch (Exception ex)
        {
            ImUtf8.Text($"Mod Directory unavailable: {ex.Message}");
        }
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
    private void Checkbox(ReadOnlySpan<byte> label, ReadOnlySpan<byte> tooltip, bool current, Action<bool> setter)
    {
        using var id = ImUtf8.PushId(label);
        var tmp = current;
        if (ImUtf8.Checkbox(""u8, ref tmp) && tmp != current)
        {
            setter(tmp);
            _configuration.Save();
        }

        ImGui.SameLine();
        ImUtf8.LabeledHelpMarker(label, tooltip);
    }
}
